spring.profiles.active=dev
server.port=8070
spring.application.name=moss

# 编码配置
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true

# JVM编码配置
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.enabled=true

#bei-jing
dashscope.api-key=sk-02a7f6f042f1405db0016b35556c91de

spring.main.allow-bean-definition-overriding=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=salesupaisass@gmail.com
spring.mail.password=hqhkeuprbgugcdwy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Redis配置
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=123456
spring.data.redis.database=0

# Email Verification Configuration
email.verification.code-length=6
email.verification.expire-minutes=10
email.verification.max-retry=3


com.sales.helper.dify.chat.api.uploadPath=.\\tmp
com.sales.helper.dify.chat.api.baseurl=https://dify.salesupaisass.com/v1
com.sales.helper.dify.chat.api.consoleBaseurl=https://dify.salesupaisass.com/console
com.sales.helper.dify.chat.api.collectApiKey=app-NTru9xgpeZrT41t2CAqDS59u
com.sales.helper.dify.chat.api.scheduleActivityKey=app-MVwQ4KhKQ1NcVOilQXu2kog5
com.sales.helper.dify.chat.api.email=1031633784@qq.com

com.sales.helper.dify.chat.api.password=liao12peng

minio.endpoint=https://ai.salesupaisass.com
minio.access-key=admin
minio.secret-key=admin123
minio.bucket-name=jodohku
minio.file-size-limit=10MB